env:
  global:
    - secure: "DIXpQDgbpXgAIujhnphavBBP5jWonN4G5cn7UHkk+vioJvd/5wkJGZOZKXYqZnO2Pe50d7WMZ5RIdgtvUT6YOGVykGIo3beT/agBNMBjd4gJyJTSEf5zYl//cy6BTt6GNFY/0E05Q3f8IiuJSkxRmMEaPHnA9+O+rlB9woTfZOo="
    - secure: "ja2aI/UwJ5mNreCoMLnAppquJhpUf1D4gfSKrTobPU/FpPUY/aUOue+jJAhWJtjjh6I/FXH+2f6HVnU8AdqEkF7HyZpAKKCxNTZvVnS3XT4fzjKv4874tCyY38Z1eN75vSo5TptrYQtVEA8G1ZGvsHPeaPvRI+1lXLkvo+ewpxQ="
language: node_js
node_js: "0.10"
install:
  - npm -g install bower
  - npm -g install jshint
  - npm install
  - yes | bower install
  - cd node_modules/intern
  - npm install --production
  - cd ../..
script:
  - jshint --exclude-path .gitignore .
  - cd ..
  - node liaison/node_modules/intern/bin/intern-client.js config=liaison/tests/intern
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" ]]; then node liaison/node_modules/intern/runner.js config=liaison/tests/sauce; fi
